### ISSUE TITLE
GeofencesChangeEvent on property:  returned geofences with null extras

### ISSUE THREAD

**Issue by joaolh** [transistorsoft/flutter_background_geolocation#110]
## Your Environment
* Plugin version: 1.2.1
* Platform: Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config: geofence changes event is activated
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior
returned geofence list from "on" property of GeofencesChangeEvent must have extras populated with extra information as the extras had being populated when geofences were created.   

## Actual Behavior
geofence has extras are null object instead of the original populated values

## Steps to Reproduce

1.create geofence with extras
2.when GeofencesChangeEvent occurs observe that the extras is null object
4.note: the querying geofences using BackgroundGeolocation.geofences is however work fine, e.g. the extras are there. 

## Context
use the extras property of geofence to store additional data

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Thanks, I’ll look into it.  

What are you using `onGeofencesChange` for?

**Comment by christocracy** [comment]
Install latest from Git branch `GeofencesChangeEvent-extras`.  Let me know if that fixes you.

```yaml
dependencies:
  flutter_background_geolocation:
    git:
      url: https://github.com/transistorsoft/flutter_background_geolocation.git
      ref: GeofencesChangeEvent-extras
```
