### ISSUE TITLE
[Question] Using the package with an encrypted version of sqflite

### ISSUE THREAD

**Issue by andrewpmoore** [transistorsoft/flutter_background_geolocation#270]
We've recently started using your package and find it far more reliable than the alternatives.
We are using sqflite in our app already, but a modified version which enables encrypting the database as we need it for healthcare compliance.

So in our pubspec.yaml we overide the library with

```
dependency_overrides:
  sqflite:
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: 8f7a3899d3bd80090a8be2f68a0f285e753401e9
```

Originally this caused is issues with CachedNetworkImage library (which also uses sqflite) but their package now caters for this.

Is there any way to make this package be able to use the encrypted version too?
