### ISSUE TITLE
When trying to run with the version 1.9.0, crash

### ISSUE THREAD

**Issue by leonardoayres** [transistorsoft/flutter_background_geolocation#308]
When try to run my app using  the version 1.9.0, the compilation fails and the error below is displayed.

Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.
     Searched in the following locations:
     .
     .
     .
Required by:
         project :app > project :flutter_background_geolocation

And the error below:

Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
     .
     .
     .
Required by:
         project :app > project :background_fetch

**Comment by christocracy** [comment]
See the [CHANGELOG](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/CHANGELOG.md)

**Comment by leonardoayres** [comment]
Thank you.

After added the maven configuration, the new error is:

class FetchStreamHandler implements EventChannel.StreamHandler, BackgroundFetch.Callback {
    ^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture fingerprint of output files for task ':background_fetch:compileDebugJavaWithJavac' property 'destinationDir' during up-to-date check.
> Could not read path 'E:\Projetos\ProppyApp.Flutter\build\background_fetch\intermediates\javac\debug\compileDebugJavaWithJavac\classes\com\transistorsoft\flutter\backgroundfetch'.

**Comment by christocracy** [comment]
Show me your `android/build.gradle`

**Comment by leonardoayres** [comment]
buildscript {
    ext.kotlin_version = '1.3.11'
    ext {
        compileSdkVersion = 29                // or higher
        targetSdkVersion  = 29                // or higher
        appCompatVersion  = "1.0.2"           // or higher
        playServicesLocationVersion = "17.0.0"  // or higher
    }
    repositories {
        google()
        jcenter()
    }

    dependencies {
        //classpath 'com.android.tools.build:gradle:3.2.1'
        classpath 'com.android.tools.build:gradle:3.3.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.2'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven {
           // [required] flutter_background_geolocation
           url "${project(':flutter_background_geolocation').projectDir}/libs"
       }
       maven {
           // [required] background_fetch
           url "${project(':background_fetch').projectDir}/libs"
       }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"    
    project.evaluationDependsOn(':app')
        afterEvaluate {project ->
            if (project.hasProperty("android")) {
                android {
                    compileSdkVersion 29
                    buildToolsVersion '29.0.2'
                }
            }
        }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by christocracy** [comment]
`pubspec.lock`

**Comment by leonardoayres** [comment]
```
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  after_layout:
    dependency: "direct main"
    description:
      name: after_layout
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.7+2"
  archive:
    dependency: transitive
    description:
      name: archive
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.13"
  args:
    dependency: transitive
    description:
      name: args
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.6.0"
  assorted_layout_widgets:
    dependency: "direct main"
    description:
      name: assorted_layout_widgets
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.4.1"
  background_fetch:
    dependency: transitive
    description:
      name: background_fetch
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.0"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  cached_network_image:
    dependency: "direct main"
    description:
      name: cached_network_image
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.0+1"
  camera:
    dependency: "direct main"
    description:
      name: camera
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.8+2"
  charcode:
    dependency: transitive
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.3"
  clock:
    dependency: transitive
    description:
      name: clock
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.14.12"
  connectivity:
    dependency: "direct main"
    description:
      name: connectivity
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.8+6"
  connectivity_macos:
    dependency: transitive
    description:
      name: connectivity_macos
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.0+3"
  connectivity_platform_interface:
    dependency: transitive
    description:
      name: connectivity_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.5"
  convert:
    dependency: transitive
    description:
      name: convert
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.1"
  crypto:
    dependency: transitive
    description:
      name: crypto
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.4"
  csslib:
    dependency: transitive
    description:
      name: csslib
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.16.1"
  cupertino_icons:
    dependency: "direct main"
    description:
      name: cupertino_icons
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.2"
  device_apps:
    dependency: "direct main"
    description:
      name: device_apps
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.9"
  dio:
    dependency: transitive
    description:
      name: dio
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.9"
  equatable:
    dependency: transitive
    description:
      name: equatable
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.1"
  file:
    dependency: transitive
    description:
      name: file
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.1.0"
  firebase:
    dependency: transitive
    description:
      name: firebase
      url: "https://pub.dartlang.org"
    source: hosted
    version: "7.2.1"
  firebase_core:
    dependency: "direct main"
    description:
      name: firebase_core
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.3+3"
  firebase_core_platform_interface:
    dependency: transitive
    description:
      name: firebase_core_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.4"
  firebase_core_web:
    dependency: transitive
    description:
      name: firebase_core_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.1+2"
  firebase_messaging:
    dependency: "direct main"
    description:
      name: firebase_messaging
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.0.12"
  fluster:
    dependency: "direct main"
    description:
      name: fluster
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.2"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_background_geolocation:
    dependency: "direct main"
    description:
      name: flutter_background_geolocation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.9.0"
  flutter_cache_manager:
    dependency: transitive
    description:
      name: flutter_cache_manager
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.2"
  flutter_datetime_picker:
    dependency: "direct main"
    description:
      name: flutter_datetime_picker
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.8"
  flutter_html:
    dependency: "direct main"
    description:
      name: flutter_html
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.1"
  flutter_local_notifications:
    dependency: "direct main"
    description:
      name: flutter_local_notifications
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.8.4"
  flutter_localizations:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_permissions_helper:
    dependency: "direct main"
    description:
      name: flutter_permissions_helper
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.4"
  flutter_plugin_android_lifecycle:
    dependency: transitive
    description:
      name: flutter_plugin_android_lifecycle
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.5"
  flutter_polyline_points:
    dependency: "direct main"
    description:
      name: flutter_polyline_points
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.0"
  flutter_rounded_date_picker:
    dependency: "direct main"
    description:
      name: flutter_rounded_date_picker
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.4"
  flutter_sms:
    dependency: "direct main"
    description:
      name: flutter_sms
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  flutter_speed_dial:
    dependency: "direct main"
    description:
      name: flutter_speed_dial
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.5"
  flutter_svg:
    dependency: "direct main"
    description:
      name: flutter_svg
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.17.4"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_web_plugins:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.0"
  geocoder:
    dependency: "direct main"
    description:
      name: geocoder
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.1"
  geolocator:
    dependency: "direct main"
    description:
      name: geolocator
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.3.1"
  google_api_availability:
    dependency: transitive
    description:
      name: google_api_availability
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.4"
  google_map_polyline:
    dependency: "direct main"
    description:
      name: google_map_polyline
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0+1"
  google_maps_flutter:
    dependency: "direct main"
    description:
      name: google_maps_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.28+1"
  google_maps_flutter_platform_interface:
    dependency: transitive
    description:
      name: google_maps_flutter_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  html:
    dependency: transitive
    description:
      name: html
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.14.0+3"
  http:
    dependency: transitive
    description:
      name: http
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.0+2"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.3"
  image:
    dependency: transitive
    description:
      name: image
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.12"
  image_picker:
    dependency: "direct main"
    description:
      name: image_picker
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.6+5"
  image_picker_platform_interface:
    dependency: transitive
    description:
      name: image_picker_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  intl:
    dependency: "direct main"
    description:
      name: intl
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.16.1"
  js:
    dependency: transitive
    description:
      name: js
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.1+1"
  location:
    dependency: "direct main"
    description:
      name: location
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.2"
  location_permissions:
    dependency: "direct main"
    description:
      name: location_permissions
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.5"
  location_platform_interface:
    dependency: transitive
    description:
      name: location_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  location_web:
    dependency: transitive
    description:
      name: location_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  matcher:
    dependency: transitive
    description:
      name: matcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.6"
  matrix4_transform:
    dependency: transitive
    description:
      name: matrix4_transform
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.3"
  meta:
    dependency: transitive
    description:
      name: meta
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.8"
  package_info:
    dependency: "direct main"
    description:
      name: package_info
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.0+17"
  path:
    dependency: transitive
    description:
      name: path
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.6.4"
  path_drawing:
    dependency: transitive
    description:
      name: path_drawing
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.1"
  path_parsing:
    dependency: transitive
    description:
      name: path_parsing
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.4"
  path_provider:
    dependency: "direct main"
    description:
      name: path_provider
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.6.7"
  path_provider_macos:
    dependency: transitive
    description:
      name: path_provider_macos
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.4"
  path_provider_platform_interface:
    dependency: transitive
    description:
      name: path_provider_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  pedantic:
    dependency: transitive
    description:
      name: pedantic
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.0+1"
  permission_handler:
    dependency: "direct main"
    description:
      name: permission_handler
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.0.0+hotfix.8"
  permission_handler_platform_interface:
    dependency: transitive
    description:
      name: permission_handler_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  petitparser:
    dependency: transitive
    description:
      name: petitparser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.4.0"
  platform:
    dependency: transitive
    description:
      name: platform
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.1"
  plugin_platform_interface:
    dependency: transitive
    description:
      name: plugin_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  provider:
    dependency: "direct main"
    description:
      name: provider
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.2.0"
  quiver:
    dependency: transitive
    description:
      name: quiver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.3"
  rxdart:
    dependency: transitive
    description:
      name: rxdart
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.24.0"
  shared_preferences:
    dependency: "direct main"
    description:
      name: shared_preferences
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.7+1"
  shared_preferences_macos:
    dependency: transitive
    description:
      name: shared_preferences_macos
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.1+4"
  shared_preferences_platform_interface:
    dependency: transitive
    description:
      name: shared_preferences_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  shared_preferences_web:
    dependency: transitive
    description:
      name: shared_preferences_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.2+3"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  source_span:
    dependency: transitive
    description:
      name: source_span
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.7.0"
  sqflite:
    dependency: transitive
    description:
      name: sqflite
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.0+1"
  sqflite_common:
    dependency: transitive
    description:
      name: sqflite_common
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.9.3"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  stream_transform:
    dependency: transitive
    description:
      name: stream_transform
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.5"
  synchronized:
    dependency: transitive
    description:
      name: synchronized
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0+1"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  test_api:
    dependency: transitive
    description:
      name: test_api
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.15"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.6"
  unicorndial:
    dependency: "direct main"
    description:
      name: unicorndial
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.5"
  url_launcher:
    dependency: "direct main"
    description:
      name: url_launcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.4.2"
  url_launcher_macos:
    dependency: transitive
    description:
      name: url_launcher_macos
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.1+4"
  url_launcher_platform_interface:
    dependency: transitive
    description:
      name: url_launcher_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.6"
  url_launcher_web:
    dependency: transitive
    description:
      name: url_launcher_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.1+1"
  uuid:
    dependency: transitive
    description:
      name: uuid
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.8"
  wakelock:
    dependency: "direct main"
    description:
      name: wakelock
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.4+1"
  xml:
    dependency: "direct main"
    description:
      name: xml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.6.1"
sdks:
  dart: ">=2.8.0 <3.0.0"
  flutter: ">=1.16.3 <2.0.0"

```
