### ISSUE TITLE
Wrong format in extras when list have maps items

### ISSUE THREAD

**Issue by upmauro** [transistorsoft/flutter_background_geolocation#335]
## Your Environment
* Plugin version: 1.8.0
* Platform: Android
* OS version: All
* Device manufacturer / model: All
* Flutter info (`flutter doctor`): All
```

Expected Behavior
Extras data in location needs to be recursive when have list Map too.

## Actual Behavior
Extras convert Maps inside list to string array.

## Steps to Reproduce

{
  "extras": {
    "foo": [
      {
        "foor": "bar"
      }
    ]
  }
}

## Context

https://github.com/transistorsoft/flutter_background_geolocation/blob/f4efcbf95ddecdb847bf448a393d2f5f79d1d482/android/src/main/java/com/transistorsoft/flutter/backgroundgeolocation/BackgroundGeolocationModule.java#L911

need to be recursive if the item from list is Map

**Comment by christocracy** [comment]
>Plugin version: All

Please update the issue and provide the **exact** plugin version you're dealing with, for the benefit of others in the future.

>Platform: All

I don't believe this is true.

**Comment by upmauro** [comment]
> > Plugin version: All
> 
> Please update the issue and provide the **exact** plugin version you're dealing with, for the benefit of others in the future.
> 
> > Platform: All
> 
> I don't believe this is true.

Fixed.

**Comment by christocracy** [comment]
Try installing from Github branch `android-extras-array`

```yaml
dependencies:
  flutter_background_geolocation:
    git:
      url: https://github.com/transistorsoft/flutter_background_geolocation.git
      ref: android-extras-array
```
